export const QUERY_KEY = {
  LOGIN: "LOGIN",
  REGISTER: "REGISTER",
  TASK: {
    LIST: "TASK_LIST_BY_USER",
    DETAIL: "TASK_DETAIL",
    CREATE: "TASK_CREATE",
    UPDATE: "TASK_UPDATE",
    DELETE: "TASK_DELETE",
  },
  STATUS: {
    LIST: "STATUS_LIST_BY_USER",
    DETAIL: "STATUS_DETAIL",
    CREATE: "STATUS_CREATE",
    UPDATE: "STATUS_UPDATE",
    DELETE: "STATUS_DELETE",
  },
};
